apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

bases:
  - ../../config

resources:
  - manager/loadbalancer.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1beta1
      kind: Deployment
      name: clusterapi-controllers
    path: manager/patch.yaml
