---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  infrastructureRef:
    kind: OpenStackCluster
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    name: ${CLUSTER_NAME}
    namespace: ${CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: OpenStackCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  tags:
  - a_cluster_wide_tag
  cloudName: $CLOUD
  cloudsSecret:
    name: cloud-config
    namespace: capo-system
