- hosts: all
  become: yes
  roles:
  - move-k8s-repo-to-k8s-specific-dir
  - export-cloud-openrc
  tasks:
  - name: Test
    shell:
      cmd: |

        openstack server list
        openstack flavor list
        
        cat /sys/module/kvm_intel/parameters/nested

        sudo rmmod kvm-intel
        sudo sh -c "echo 'options kvm-intel nested=y' >> /etc/modprobe.d/dist.conf"
        sudo modprobe kvm-intel

        cat /sys/module/kvm_intel/parameters/nested


        modinfo kvm_intel | grep nested

        modinfo kvm_intel

        cat /proc/cpuinfo
        cat /proc/meminfo

      executable: /bin/bash
      chdir: '{{ k8s_os_capi_provider_src_dir }}'
    environment: '{{ global_env }}'
