apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: clusterapi-controllers
  namespace: openstack-provider-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31102
    port: 31000
    protocol: TCP
    targetPort: 31000
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  sessionAffinity: None
  type: LoadBalancer
